FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB gin_pron
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD admin123

# Copy initialization scripts
COPY init.sql /docker-entrypoint-initdb.d/

# Expose PostgreSQL default port
EXPOSE 5432
