version: '3.8'
services:
  app:
    build: .
    environment:
      DB_HOST: local
      DB_USER: admin
      DB_NAME: gin_pro1
      DB_PASSWORD: admin123
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: gin_pro1
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"